### PR TITLE
fix observers

### LINKED ISSUE #95: Sponsored ad got through on 1.9.3 in Chrome
All was good, then I just saw this Sponsored ad. Running 1.9.3 in Chrome. Still, better than it was in 1.9.2 for me.
Now...to get rid of all the "Suggested for You" ads!

image

### PR DESCRIPTION
**Pull request by cbotsikas**
Fixes #95

### CODE REVIEW

File: src/fb5.js [hunk 1]
```diff
@@ -234,18 +239,46 @@ function setupPageObserver() {
...
+    cleanupWatchObserver();
   }
 });
+function cleanupPageObserver() {
+  if (pageObserver === null) return;
+  pageObserver.__observed &&
+    delete feedObserver.__observed.dataset.adblockObserved &&
+    delete feedObserver.__observed;
+  pageObserver.disconnect();
+  // do not nullify pageObserver!
```
Comment (tiratatp) [inline src/fb5.js:258]: Can you clarify why we cannot do this?

File: src/fb5.js [hunk 2]
```diff
@@ -136,14 +142,12 @@ function setWatchObserver() {
 function onPageChange() {
   if (isFBWatch()) {
     if (feedObserver !== null) {
```
Comment (tiratatp) [inline src/fb5.js:144]: We don't need this check here anymore right? Since we have the same check inside `cleanupFeedObserver`?

File: src/fb5.js [hunk 3]
```diff
@@ -136,14 +142,12 @@ function setWatchObserver() {
...
-      feedObserver.disconnect();
-      feedObserver = null;
+      cleanupFeedObserver();
     }
     onPageChangeInWatch();
   } else {
     if (watchObserver !== null) {
```
Comment (tiratatp) [inline src/fb5.js:149]: Same as above

File: src/fb5.js [hunk 4]
```diff
@@ -234,18 +239,46 @@ function setupPageObserver() {
...
   }
 
   if (watchObserver !== null) {
-    watchObserver.disconnect();
-    watchObserver = null;
+    cleanupWatchObserver();
   }
 });
+function cleanupPageObserver() {
+  if (pageObserver === null) return;
```
Comment (tiratatp) [inline src/fb5.js:253]: nit: I'm not a fan of `if` without brace

File: src/fb5.js [hunk 5]
```diff
@@ -234,18 +239,46 @@ function setupPageObserver() {
...
+  pageObserver.__observed &&
+    delete feedObserver.__observed.dataset.adblockObserved &&
+    delete feedObserver.__observed;
```
Comment (tiratatp) [inline src/fb5.js:256]: nit: I'm not a fan for shorthand condition. Is there a reason why we should prefer this over a full `if`?

**Review by tiratatp — CHANGES_REQUESTED** [review]
A few minor comments

File: src/fb5.js (hunk 1 above)
Comment (cbotsikas) [reply src/fb5.js:258]: Actually we could clear the pageObserver too at this point since this cleanupPageObserver is only called when the beforeunload event triggers, meaning that page will change and if facebook is reloaded, the script will rerun and initialization will occur [on line 205](https://github.com/siradar/facebook_adblock/blob/master/src/fb5.js#L205). The only reason not to nullify it here is because we don't have a mechanism to initiate it again, like we do with the rest observers, without re-running the script.

File: src/fb5.js (hunk 2 above)
Comment (cbotsikas) [reply src/fb5.js]: changed

File: src/fb5.js (hunk 3 above)
Comment (cbotsikas) [reply src/fb5.js]: changed

File: src/fb5.js (hunk 4 above)
Comment (cbotsikas) [reply src/fb5.js]: changed

File: src/fb5.js (hunk 5 above)
Comment (cbotsikas) [reply src/fb5.js]: changed. 
This particular block had also a typo where I didn't change the feedObserver to pageObserver when I copy-pasted that block. It's also fixed

**Review by tiratatp — APPROVED** [review]
LGTM

File: src/fb5.js [hunk 6]
```diff
@@ -234,18 +235,51 @@ function setupPageObserver() {
 
 // cleanup
 window.addEventListener("beforeunload", () => {
+  cleanupPageObserver();
+  cleanupFeedObserver();
+  cleanupWatchObserver();
```
Comment (tiratatp) [inline src/fb5.js:240]: Is the order wrong? Since if you call `cleanupPageObserver()` first then the `cleanupFeedObserver()` will no no-op .

Should it be,
```
  cleanupFeedObserver();
  cleanupWatchObserver();
  cleanupPageObserver();
```

**Review by tiratatp — CHANGES_REQUESTED** [review]
Sorry. One comment about `beforeunload`.

File: src/fb5.js (hunk 6 above)
Comment (cbotsikas) [reply src/fb5.js:240]: The observers and the variables holding them are independent so the order shouldn't matter. Do you want to change that?

Comment (tiratatp) [reply src/fb5.js:240]: Oh sorry I was a dummy. I saw a check for `if (feedObserver !== null)` in `cleanupPage` but that was deleted. lol

**Review by tiratatp — APPROVED** [review]

**Comment by tiratatp** [comment]
@cbotsikas could you see if you could sign the commit next time? https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification

I got this warning myself too and I haven't fixed mine.

So don't worry about this time. But let's aim to fix by our next PR. 😄

**Comment by cbotsikas** [comment]
@tiratatp will you bump and publish a new version?
